"""Auto: 2025-11-26 20:15

Revision ID: 175109880801
Revises: f1785a92fda3
Create Date: 2025-11-26 20:15:01.686544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175109880801'
down_revision: Union[str, None] = 'f1785a92fda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casos_teste', sa.Column('responsavel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'casos_teste', 'usuarios', ['responsavel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'casos_teste', type_='foreignkey')
    op.drop_column('casos_teste', 'responsavel_id')
    # ### end Alembic commands ###
