"""Auto: 2026-01-28 14:47

Revision ID: 33675e26ce19
Revises: 790f8ca14ef8
Create Date: 2026-01-28 14:47:33.493790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33675e26ce19'
down_revision: Union[str, None] = '790f8ca14ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_sistema_id', table_name='logs_sistema')
    op.drop_table('logs_sistema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_sistema',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entidade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entidade_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detalhes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='logs_sistema_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='logs_sistema_pkey')
    )
    op.create_index('ix_logs_sistema_id', 'logs_sistema', ['id'], unique=False)
    # ### end Alembic commands ###
