"""Auto: 2026-01-14 18:34

Revision ID: de4fecd62a71
Revises: 6672af2766df
Create Date: 2026-01-14 18:34:13.772022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4fecd62a71'
down_revision: Union[str, None] = '6672af2766df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casos_teste', sa.Column('ciclo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'casos_teste', 'ciclos_teste', ['ciclo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'casos_teste', type_='foreignkey')
    op.drop_column('casos_teste', 'ciclo_id')
    # ### end Alembic commands ###
